### ISSUE TITLE
Installing eva in Giotto case

### ISSUE THREAD

**Issue by xiao-kong-long** [JinmiaoChenLab/SEDR_analyses#2]
Hello,
When I tried to run Giotto case to DLPFC, I met a problem: eva package couldn't be installed correctly.
I wonder know how you solve it, it's very important to me.
Thanks very much !

**Comment by Xuhang01** [comment]
Hi Xiao-kong-long,

Could you elaborate your question more explicitly? For example, copy and paste the error message.

By the way, I think you can also ask for help on Giotto github page.

Best,
Xuhang01

**Comment by xiao-kong-long** [comment]
Thanks for your reply, I've given up Giotto as baseline because of its complexity. Have a nice day !
