### ISSUE TITLE
ground truth of other 10x visium datasets

### ISSUE THREAD

**Issue by xiao-kong-long** [JinmiaoChenLab/SEDR_analyses#3]
Hello, 
I wanna get ground truth file of other 10x visium datasets.
Could you provide some solution ?
Thanks!

**Comment by Xuhang01** [comment]
Hi xiao-kong-long,

The ground truth for ST data is usually generated by manually annotation. If you want to find the ground truth for pulic data, you should read the original papers carefully. If you want to get the ground truth for your inhouse data, you should better find some biologists who are familiar with the tissue to help you making the annotation.

**Comment by xiao-kong-long** [comment]
It's useful! Thank you very much.
