### ISSUE TITLE
NameError: name 'logg' is not defined

### ISSUE THREAD

**Issue by 0225yyyyyqq** [JinmiaoChenLab/SEDR_analyses#7]
. I encountered an error while running the command "python DLPFC_stLearn.py 151507". Could you please assist me in resolving this issue?
Traceback (most recent call last):
  File "DLPFC_stLearn.py", line 24, in <module>
    data = st.Read10X(BASE_PATH / sample)
  File "C:\Users\123\anaconda3\envs\stlearn\lib\site-packages\stlearn\wrapper\read.py", line 118, in Read10X
    logg.warning(
NameError: name 'logg' is not defined

**Comment by Xuhang01** [comment]
It means that you have not put tissue_hires_image.png and tissue_lowres_image.png under spatial folder. Please manage your inputs with the structure we introduced in README.

**Comment by 0225yyyyyqq** [comment]
> It means that you have not put tissue_hires_image.png and tissue_lowres_image.png under spatial folder. Please manage your inputs with the structure we introduced in README.

Thank you for your assistance. The issue has been resolved. Additionally, I would appreciate it if you could provide guidance on the location of the full_image.tif file.

**Comment by Xuhang01** [comment]
You can find the full image of DLPFC dataset from here: https://github.com/LieberInstitute/HumanPilot/. Just search for "image_full" in that page and you will get it.

**Comment by 0225yyyyyqq** [comment]
Thank you much
        
            
        
    
         
        
            
                        ***@***.***
            
        
     
        
  
    ---- Replied Message ----
  
  
    
      
        
         From 
        
        
            ***@***.***>
            
        
      
      
        
         Date 
        
        
        10/9/2023 10:04
        
      
      
        
         To 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         Cc 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         Subject 
        
        
              Re: [JinmiaoChenLab/SEDR_analyses] NameError: name 'logg' is not defined (Issue #7)
        
      
    
  

You can find the full image of DLPFC dataset from here: https://github.com/LieberInstitute/HumanPilot/. Just search for "image_full" in that page and you will get it.
