### ISSUE TITLE
clustered results

### ISSUE THREAD

**Issue by zhubbbzhu** [JinmiaoChenLab/SEDR_analyses#9]
Excuse me, in SpaGCN's DLPFC ,how to create a visualization where the clustered results are displayed directly on the original image instead of generating a new plot?Thanks!

**Comment by Xuhang01** [comment]
@zhubbbzhu    I do not quite understand what your problem is. Could you give me your code that you have difficulties?

**Comment by zhubbbzhu** [comment]
Thanks!I have already sent an email and hope to get your reply! Thanks!
